version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
       - echo Building...
       - mvn install
       - echo Finished build.
  post_build:
    commands:
       - echo Syncing site to S3 bucket...
       - export LC_ALL=C.UTF-8
       - cd dist && aws s3 sync --cache-control max-age=86400 --acl public-read --delete . "${S3_BUCKET_URL}"
       - echo Finished sync