version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk8
  pre_build:
    commands:
  build:
    commands:
       - echo Building...
       - mvn install
       - echo Finished build.
  post_build:
    commands:
       - echo Finished